format = """
$directory\
$username\
$hostname\
$git_branch\
$all"""
[username]
style_root = "bold red"
style_user = "bold blue"
format = "[$user]($style) "
[hostname]
style = "green"
format = "[$ssh_symbol$hostname]($style)"
[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
symbol = "ðŸŒ± "
truncation_symbol = ""
